const FLAGS: Record<string, string> = {
  'México':               'mx',
  'Sudáfrica':            'za',
  'Corea del Sur':        'kr',
  'Chequia':              'cz',
  'Canadá':               'ca',
  'Bosnia y Herzegovina': 'ba',
  'Catar':                'qa',
  'Suiza':                'ch',
  'Brasil':               'br',
  'Marruecos':            'ma',
  'Haití':                'ht',
  'Escocia':              'gb-sct',
  'Estados Unidos':       'us',
  'Paraguay':             'py',
  'Australia':            'au',
  'Turquía':              'tr',
  'Alemania':             'de',
  'Curazao':              'cw',
  'Costa de Marfil':      'ci',
  'Ecuador':              'ec',
  'Países Bajos':         'nl',
  'Japón':                'jp',
  'Suecia':               'se',
  'Túnez':                'tn',
  'Bélgica':              'be',
  'Egipto':               'eg',
  'Irán':                 'ir',
  'Nueva Zelanda':        'nz',
  'España':               'es',
  'Cabo Verde':           'cv',
  'Arabia Saudita':       'sa',
  'Uruguay':              'uy',
  'Francia':              'fr',
  'Senegal':              'sn',
  'Iraq':                 'iq',
  'Noruega':              'no',
  'Argentina':            'ar',
  'Argelia':              'dz',
  'Austria':              'at',
  'Jordania':             'jo',
  'Portugal':             'pt',
  'Congo RD':             'cd',
  'Uzbekistán':           'uz',
  'Colombia':             'co',
  'Inglaterra':           'gb-eng',
  'Croacia':              'hr',
  'Ghana':                'gh',
  'Panamá':               'pa',
}

export function flagUrl(equipo: string): string {
  const code = FLAGS[equipo]
  return code ? `https://flagcdn.com/w20/${code}.png` : ''
}
